# Generated by Django 4.0.1 on 2022-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
