# Generated by Django 4.0.1 on 2022-01-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_wikipage_text_alter_wikipage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='links',
            field=models.JSONField(default=dict),
        ),
    ]
