# Generated by Django 4.0.1 on 2022-01-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikipage_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='links',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='links',
            field=models.ManyToManyField(to='wiki.WikiPage', verbose_name='Links'),
        ),
    ]
