# Generated by Django 4.0.1 on 2022-01-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_wikipage_counter'),
        ('wiki', '0004_remove_wikipage_links_wikipage_links'),
    ]

    operations = [
    ]
