version: '3.1'

services:
  db:
    container_name: wiki-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
  wiki:
    container_name: wiki-app
    image: wiki-demo
    restart: unless-stopped
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_PORT: "${DB_PORT}"
      HOST: "${HOST}"
      PORT: "${PORT}"
      WORKERS: "${WORKERS}"
    ports:
      - ${PORT}:${PORT}
    links:
      - "db:${DB_HOST}"
    depends_on:
      - "db"