version: '3.1'

services:
  db:
    container_name: wiki-db-dev
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - 5444:5432